package Modelo;
// Generated 24-nov-2017 2:45:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CarroCompras generated by hbm2java
 */
public class CarroCompras  implements java.io.Serializable {


     private Integer idCarroCompras;
     private Usuario usuario;
     private String estado;
     private Set pedidos = new HashSet(0);
     private Set productos = new HashSet(0);

    public CarroCompras() {
    }

	
    public CarroCompras(Usuario usuario, String estado) {
        this.usuario = usuario;
        this.estado = estado;
    }
    public CarroCompras(Usuario usuario, String estado, Set pedidos, Set productos) {
       this.usuario = usuario;
       this.estado = estado;
       this.pedidos = pedidos;
       this.productos = productos;
    }
   
    public void agregarProducto(Producto producto) {
        this.productos.add(producto);
    }
    
    public Integer getIdCarroCompras() {
        return this.idCarroCompras;
    }
    
    public void setIdCarroCompras(Integer idCarroCompras) {
        this.idCarroCompras = idCarroCompras;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


