package Modelo;
// Generated 24-nov-2017 2:45:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private CarroCompras carroCompras;
     private double monto;
     private Date fecha;
     private String medioPago;
     private Set documentos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(CarroCompras carroCompras, double monto, Date fecha, String medioPago) {
        this.carroCompras = carroCompras;
        this.monto = monto;
        this.fecha = fecha;
        this.medioPago = medioPago;
    }
    public Pedido(CarroCompras carroCompras, double monto, Date fecha, String medioPago, Set documentos) {
       this.carroCompras = carroCompras;
       this.monto = monto;
       this.fecha = fecha;
       this.medioPago = medioPago;
       this.documentos = documentos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public CarroCompras getCarroCompras() {
        return this.carroCompras;
    }
    
    public void setCarroCompras(CarroCompras carroCompras) {
        this.carroCompras = carroCompras;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


