package Modelo;
// Generated 24-nov-2017 2:45:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Accesorio accesorio;
     private Vehiculo vehiculo;
     private Set catalogos = new HashSet(0);
     private Set carroComprases = new HashSet(0);

    public Producto() {
    }

    public Producto(Accesorio accesorio, Vehiculo vehiculo, Set catalogos, Set carroComprases) {
       this.accesorio = accesorio;
       this.vehiculo = vehiculo;
       this.catalogos = catalogos;
       this.carroComprases = carroComprases;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Accesorio getAccesorio() {
        return this.accesorio;
    }
    
    public void setAccesorio(Accesorio accesorio) {
        this.accesorio = accesorio;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Set getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(Set catalogos) {
        this.catalogos = catalogos;
    }
    public Set getCarroComprases() {
        return this.carroComprases;
    }
    
    public void setCarroComprases(Set carroComprases) {
        this.carroComprases = carroComprases;
    }




}


