package Modelo;
// Generated 24-nov-2017 2:45:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RolUsuario generated by hbm2java
 */
public class RolUsuario  implements java.io.Serializable {


     private Integer idRolUsuario;
     private String tipo;
     private Set usuarios = new HashSet(0);

    public RolUsuario() {
    }

	
    public RolUsuario(String tipo) {
        this.tipo = tipo;
    }
    public RolUsuario(String tipo, Set usuarios) {
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRolUsuario() {
        return this.idRolUsuario;
    }
    
    public void setIdRolUsuario(Integer idRolUsuario) {
        this.idRolUsuario = idRolUsuario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


