package Modelo;
// Generated 24-nov-2017 2:45:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Catalogo catalogo;
     private RolUsuario rolUsuario;
     private String nombreUsuario;
     private String nombre;
     private String apellido;
     private String clave;
     private Set carroComprases = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Catalogo catalogo, RolUsuario rolUsuario, String nombreUsuario, String nombre, String apellido, String clave) {
        this.catalogo = catalogo;
        this.rolUsuario = rolUsuario;
        this.nombreUsuario = nombreUsuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.clave = clave;
    }
    public Usuario(Catalogo catalogo, RolUsuario rolUsuario, String nombreUsuario, String nombre, String apellido, String clave, Set carroComprases) {
       this.catalogo = catalogo;
       this.rolUsuario = rolUsuario;
       this.nombreUsuario = nombreUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.clave = clave;
       this.carroComprases = carroComprases;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Catalogo getCatalogo() {
        return this.catalogo;
    }
    
    public void setCatalogo(Catalogo catalogo) {
        this.catalogo = catalogo;
    }
    public RolUsuario getRolUsuario() {
        return this.rolUsuario;
    }
    
    public void setRolUsuario(RolUsuario rolUsuario) {
        this.rolUsuario = rolUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getCarroComprases() {
        return this.carroComprases;
    }
    
    public void setCarroComprases(Set carroComprases) {
        this.carroComprases = carroComprases;
    }




}


